README.md
Signed-off-by: Evan Freed <evan@elastic.co>
Very small fix to remove a bracket.
=> Broken Documentation URL Fix

api/apidocs.json, go.sum, pkg/client/deployments/create_deployment_responses.go, pkg/client/deployments/deployments_client.go
Fixes a mismatch between the actual status code (201) and the defined
status code.
=> client: Fix deployment create response code to 201

pkg/util/slice/string.go, pkg/util/slice/string_test.go
Moves the `StringSlice` structure from Soteria in here
Meta-issue : https://github.com/elastic/soteria/issues/644
See meta-issue
=> move string slice from soteria

.gitignore, build/Makefile.deps, scripts/uname_arch.sh
This PR updates the deps makefile target to use make's inbuilt cache capabilities.
The main features are:
- cached binary dependencies
- versioned binary dependencies
- faster makefile targets which rely on the deps target
The main issue that this PR solves is that quite a few makefile targets depend on the `deps` target. The `deps` target currently pulls the binaries down each time it's invoked which is a lengthly time sink.
`make deps`
=> makefile: using caching in deps target

pkg/plan/track.go, pkg/plan/track_test.go
Fixes a bug in the plan tracker logic which made it return the first
step which finished with status "error" rather than the last step. This
has many downstream effects but more notably, makes vacates miss the end
result of the vacate and potentially set a cluster vacate as "Sucessful"
when it is not.
Vacates marked as successful when not.
Relates to https://github.com/elastic/soteria/issues/688
=> plan: Fix bug where last step error was missed

.github/workflows/go.yml, pkg/api/version.go
Updates the API version to match the spec version
=> api: Update API version to 2.5.0

.github/CODEOWNERS
=> misc: update codeowners

pkg/plan/doc.go
This PR fixes typo in docs
This PR fixes typo in docs
=> Fix typo in docs in pkg/plan

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/GENERIC_QUESTION.md
Updates GH issue templates to reflect new team label
=> misc: update issue template labels

pkg/util/ec/rand.go, pkg/util/ec/rand_test.go
I forgot to commit the unit tests I wrote for #107.
#107
=> ec: Add missing rand unit tests

pkg/api/platformapi/info.go, pkg/api/platformapi/info_test.go
This patch modifies all the platformapi public functions to have a
Region string required parameter which is then used to create a new
context.Context: api.WithRegion(context.Background(), params.Region)
and pass it as the API operation context.
Unit tests have been modified to include a request
assertion which ensures that the region path interpolation is used when
the /platform APIs are being called.
Part of #129
=> platformapi: Add region parameter to all APIs

internal/pkg/apivalidator/request.go
Fixes a bug in the apivalidator where PATCH requests weren't being populated with an empty body.
Running the tests manually
=> apivalidator: Add empty body to PATCH requests

build/Makefile.apivalidation, internal/pkg/apivalidator/request.go
The new deployment templates endpoint requires a query.
This change to the apivalidator request builder accounts for that.
flaky test
manually by running the test
=> apivalidator: Modifies the request builder to take into account required query

CONTRIBUTING.md, README.md
In addition to fixing a broken link, this patch improves our documentation 
by providing up to date information about the cloud-sdk-go structure and
how to leverage it.
Closes: https://github.com/elastic/cloud-sdk-go/issues/172
=> docs: Improve README and CONTRIBUTING docs with updated information

pkg/api/deploymentapi/testdata/apm_get.json, pkg/api/deploymentapi/testdata/apm_update.json, pkg/api/deploymentapi/testdata/appsearch_get.json, pkg/api/deploymentapi/testdata/appsearch_update.json, pkg/api/deploymentapi/testdata/enterprise_search_get.json, pkg/api/deploymentapi/testdata/enterprise_search_update.json, pkg/api/deploymentapi/update_payload.go, pkg/api/deploymentapi/update_payload_test.go
Adds a new `NewUpdateRequest` function which allows the creation of an
Update payload from a Get deployment response.
This allows us to add a `--generate-payload` flag to  the `show` command
on `ecctl` and make it easier to update an existing deployment.
elastic/ecctl#335
Unit and ecctl tested.
=> deploymentapi: Add NewUpdateRequest function

renovate.json
Enables the use of Renovate rather than relying on dependabot.
Make all our repos use the same upgrader.
=> deps: Enable Renovate

Makefile
Updates the master tracked versions for the cloud-sdk-go and ECE to 
`v1.1.0` and `v2.7.0` respectively.
Keep master looking forward
=> release: Update version to 1.1.0 and 2.7.0

pkg/api/deploymentapi/create.go, pkg/api/deploymentapi/depresourceapi/new_payload.go
Adds new comments on `CreateParams` and `NewPayloadParams` which should
help inform our users of what each field does and if it's required or
not.
Improve our Godoc.
=> deploymentapi: Add CreateParams struct comments

go.sum, pkg/api/stackapi/delete.go, pkg/api/stackapi/get.go
Updates the `semver` import path to include the `v4` suffix.
=> stackapi: Update semver import path

pkg/api/platformapi/allocatorapi/list.go
Adds godoc style comments to each of the allocatorapi.ListParams fields.
=> allocatorapi: Add ListParams field comments

pkg/api/deploymentapi/depresourceapi/reset_es_password.go, pkg/api/deploymentapi/depresourceapi/reset_es_password_test.go
Adds a new `ResetElasticsearchPassword` with RefID auto-discovery.
Adding more API implementation of the spec.
=> depresourceapi: Add Reset elasticsearch password

pkg/util/slice/string.go, pkg/util/slice/string_test.go
Adds the following `StringSlice` receiver methods
- IsEmpty
- Contains
- ToCommaSeparatedString
This will allow us to us in a more readable way the StringSlice vars accross our code
=> adds a few StringSlice receiver methods

pkg/api/deploymentapi/testdata/observability_get.json, pkg/api/deploymentapi/testdata/observability_update.json, pkg/api/deploymentapi/update_payload.go, pkg/api/deploymentapi/update_payload_test.go
Fixes the `NewUpdateRequest` function to account for observability settings.
Related: https://github.com/elastic/ecctl/issues/407
Manually through ecctl and with tests.
=> deploymentapi: Add observability settings to NewUpdateRequest

pkg/api/stackapi/list.go, pkg/api/stackapi/list_test.go
Fixes a bug where the sorting algorithm didn't work properly on versions
with a double digit minor.
Closes #259
=> stack: Fix version sorting algorithm

pkg/util/cmdutil/flag.go, pkg/util/cmdutil/flag_test.go
Adds a function that checks if none or both flags are used.
If only one of them is used then an error is thrown
=> Adds a cmd util function to check if none or both flags are used

README.md
Fixes the broken readme example and modifies it to make it slightly
nicer to copy / modify.
Closes #256
Copying the example and running ` go run main.go`.
=> doc: Fixes broken readme example

pkg/api/deploymentapi/depresourceapi/elasticsearch.go, pkg/api/deploymentapi/depresourceapi/elasticsearch_test.go
Fixes a bug where the Plugins slice wasn't being passed down the call
stack.
=> deploymentapi: Fix excluded plugins

.github/workflows/apivalidation.yml, .github/workflows/go.yml, .golangci.yml, build/Makefile.deps, go.mod, go.sum
Updates the Go, tooling dependency and Go module versions to the latest.
=> chore: Update Go and dependency versions

README.md
Adds the Go reference badge to the README file.
Missing reference links, which made the godoc reference not easily discoverable.
=> Add Go reference badge to readme

pkg/api/deploymentapi/extensionapi/upload.go, pkg/api/deploymentapi/extensionapi/upload_test.go
Adds an API for uploading extensions
Related: https://github.com/elastic/ecctl/issues/448
This API was missing from the SDK
Unit tests
=> [extensionapi] Adds a new upload API

pkg/api/deploymentapi/extensionapi/create.go, pkg/api/deploymentapi/extensionapi/create_test.go, pkg/api/deploymentapi/extensionapi/update.go, pkg/api/deploymentapi/extensionapi/update_test.go
Adds validation on a couple of fields that are required
=> extansionapi: Add validation on required fields

pkg/api/commentapi/get.go, pkg/api/commentapi/get_params.go, pkg/api/commentapi/get_params_test.go, pkg/api/commentapi/get_test.go
Introduces a new operation to get a specific comment. 
Required by https://github.com/elastic/ecctl/issues/456
Unit tested and via `ecctl` - PR will follow
=> implements the comment get api operation

pkg/api/commentapi/update.go, pkg/api/commentapi/update_params.go, pkg/api/commentapi/update_params_test.go, pkg/api/commentapi/update_test.go
Introduces a new operation to update a specific comment of a given resource. 
Required by https://github.com/elastic/ecctl/issues/456
Unit tested and via `ecctl` - PR will follow
=> implements comment update operation

Makefile
Seems like the reasonable thing to do, updating the makefile to target the next minors for this and ECE after we released 1.3/2.9 today
=> Bump versions after releasing 1.3 for ECE 2.9.0

.github/workflows/branch.yml
Adds a GitHub action which creates a new branch when a tag is pushed
with the tag's MAJOR.MINOR. If the branch already exists, the action
will fail, but it can be ignored. GitHub actions has no way to set the
step as successful on failure, we'd need to modify the source code of
the used action.
Auto-branch on tag push.
=> release: Add branch GitHub action

pkg/api/deploymentapi/trafficfilterapi/update_payload.go, pkg/api/deploymentapi/trafficfilterapi/update_payload_test.go
Adds new functionality to build an traffic filter update request form get in order to be
able to generate an update payload in ecctl.
unit tests and by running ecctl manually
=> trafficfilterapi: create an update request from get

pkg/api/deploymentapi/trafficfilterapi/update_payload_test.go
There were changes to the apidocs which were merged before the latest
commit but the tests of this PR ran before the apidocs changes were merged
😄 
This PR fixes a broken test.
Please feel free to merge this PR once it gets approved
=> test: Update test to latest apidocs changes

api/apidocs-user.json, api/apidocs.json, pkg/client/authentication/authentication_client.go, pkg/client/deployments/deployments_client.go, pkg/client/deployments/start_deployment_resource_instances_all_maintenance_mode_parameters.go, pkg/client/deployments/start_deployment_resource_instances_all_parameters.go, pkg/client/deployments/start_deployment_resource_instances_parameters.go, pkg/client/deployments/start_deployment_resource_maintenance_mode_parameters.go, pkg/client/deployments/stop_deployment_resource_instances_all_maintenance_mode_parameters.go, pkg/client/deployments/stop_deployment_resource_instances_all_parameters.go, pkg/client/deployments/stop_deployment_resource_instances_parameters.go, pkg/client/deployments/stop_deployment_resource_maintenance_mode_parameters.go, pkg/models/cluster_metadata_settings.go, pkg/models/deployment_metadata.go, pkg/models/instance_configuration.go, pkg/models/instance_configuration_info.go
Updates the swagger spec and generated models to ECE version `2.10.0`.
=> release: Update swagger spec to ECE 2.10.0

.github/workflows/release.yml
Updates the action's credentials to use GH token with the appropriate
permissions to push to the protected branch.
=> release: Update action credentials

.github/workflows/release.yml
Fixes the github action which was failing to use the correct name to
create the GitHub release.
=> release: Fix github action changelog file

.github/workflows/apivalidation.yml, .github/workflows/go.yml, .github/workflows/release.yml, Dockerfile
Update Go version to the latest available version.
=> go: Update to latest `1.17` version

.github/workflows/release.yml
Changes the github action arguments to use the tag name that we obtain
in a previous step. This allows the github action to be patched and be
retried manually.
=> release: Explicitly specify tag for release

developer_docs/RELEASE.md
Updates the `RELEASE.md` document to reflect all the latest updates and
the automation that has been put in place.
=> release: Update `RELEASE.md` document with latest

.github/workflows/changelog_generation.yml
Automates the generation of the changelog by running `make changelog` on
every change that's merged into a repository branch.
=> release: Automate changelog generation via actions

build/Makefile.deps
=> scripts: Create version dir on versionbump targets

.changelog/1.7.0/364.yml
In https://github.com/elastic/cloud-sdk-go/pull/364 I forgot changelogs
=> Changelogs for 1.7.0

.changelog/1.8.0/367.yml, .changelog/1.8.0/369.yml, .changelog/1.8.0/374.yml, .changelog/1.8.0/375.yml, .changelog/1.8.0/377.yml, .changelog/1.8.0/378.yml, .changelog/1.8.0/379.yml, NOTICE, notes/v1.8.0.md
This PR updates NOTICE and add changelog for 1.8.0
=> Update NOTICE and add changelog for 1.8.0

.changelog/1.8.1/386.yml, pkg/plan/mock/generator.go, pkg/plan/mock/generator_test.go, pkg/plan/track_change_test.go, pkg/plan/track_response_builder.go
Adds the missing plan tracking for the `integrations_server`.
=> Add plan tracking for `integrations_server` (#386)

.github/CODEOWNERS
The wrong Github team is being added as reviewers by default.
=> Update CODEOWNERS team to control-plane-stateful-applications.

NOTICE, build/Makefile.deps, build/Makefile.dev, build/NOTICE.tmpl
The NOTICE file in this repo was broken and did not correctly list the licenses of used libraries. This PR switches to a different tool that is also used in other elastic public repos.
- The NOTICE file used to be generate by running `go-licenser`, however newer versions of that tool don't support this functionality anymore
- Instead, `go-licence-detector` is now used to generate the NOTICE.
=> Fix NOTICE generation.

.changelog/1.15.0/450.yml, .changelog/1.15.0/451.yml, notes/v1.15.0.md
Add changelog entry for 1.15.0.
=> Release 1.15.0: Add changelog

.github/workflows/release.yml
Updates the process of creating the release branch, using a similar approach to the changes made for ecctl in https://github.com/elastic/ecctl/pull/627.
The "create a github branch" job that's part of the release is failing. Example: https://github.com/elastic/cloud-sdk-go/actions/runs/7246987107.
=> Update create branch process in release workflow

.changelog/1.17.0/461.yml
=> Add changelog for #461

.changelog/1.23.0/487.yml, Makefile, notes/v1.23.0.md
Update version in Makefile and add changelog entry for 1.23.0.
=> Updates for release 1.23.0

Makefile, NOTICE, notes/v1.24.0.md
- Bump verson
- Add changelog
- Update NOTICE
=> Prepare release 1.24.0
