go.mod
go.sum
pkg/api/error.go
pkg/api/error_test.go

Adds handling of a nested `response` structure as seen on the
`go-openapi/runtime` which contains a struct wrapping an http.Response.
See: https://github.com/go-openapi/runtime/blob/master/client/response.go#L24-L28
And: https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L449

api: UnwrapError now handles nested http.Response

---

.github/workflows/go.yml

Bumps GitHub Actions to Go 1.13
Go 1.13 is the latest and greatest! And all of the team seems to be running 1.13 anyway.

Bump Go version to 1.13

---

.github/workflows/go.yml
CONTRIBUTING.md

This change both enables the running of GitHub Actions for PRs and Push
events, and adds some documentation on the contributing doc to enable
github actions on the contributor's fork.

Update CONTIBUTING to enable GitHub actions

---

pkg/api/api.go
pkg/api/config.go
pkg/api/http_transport.go
pkg/api/transport_errcatch.go

Adds a Timeout field of `time.Duration` to the `api.Config` structure,
allowing users to set the Timeout value for all API calls.
It relies on modifying the runtime/client package DefaultTimeout value,
net.Dialer and http.Client Timeout values.
Not able to specify client timeouts.

api: Add Timeout duration field to Config

---

build/Makefile.deps

Adds a SKIP_DEPCHECK flag to the Makefile which when specified, it skips
downloading the binaries on which the makefile deppends on, since it
takes a bit more time, allowing contributors to speed up the dev cycle.
`SKIP_DEPCHECK` var missing in this project but present in ecctl.

build: Add SKIP_DEPCHECK flag to Makefile

---

go.mod
pkg/sync/pool/pool_test.go

Fixes an issue where the  "TestPoolAdd/Add_succeeds" test sometimes failed when running it through GitHub actions with the following error:
```
--- FAIL: TestPoolAdd (0.02s)
--- FAIL: TestPoolAdd/Add_succeeds (0.01s)
##[error]        pool_test.go:288: Pool.Add() = [0x7678c8], want {[] [0x7678c8 0x7678c8] [{} {}]}
##[error]        pool_test.go:291: Pool.Add() error = pool: failed adding work, queue full, want <nil>
##[error]        pool_test.go:301: Pool.queue = [0x7678c8], want [0x7678c8 0x7678c8]
##[error]        pool_test.go:305: Pool.signals.added = [{}], want [{} {}]
```
**Note: While I was not able to reproduce this error again, the following was done to avoid flakiness:**
The behaviour of this test is as follows:
- The queue has 3 buffered spots 
- 2 work items are sent. 
- We're …

 test: Fix flaky 'TestPoolAdd/Add_succeeds' test 

---

pkg/api/api.go
pkg/api/client_runtime.go
pkg/api/client_runtime_test.go

Adds a new structure which implements runtime/client.ClientTransport
and allows predefined rules to call a regionless or region prefixed URL
API client.
This change is necessary since the `/deployments` path does not work
with the region interpolated in the URL.
`/deployments` API doesn't work with interpolated URL paths.
Manually

api: Add CloudClientRuntime client.Runtime wrapper

---

.golangci.yml
build/Makefile.deps

This PR 
- bumps golang-ci linter version to 1.22.2
- excludes a few linters introduced from tests and source files

bump golang-ci linter version to 1.22.2

---

pkg/logging/assert.go
pkg/logging/ecs.go
pkg/logging/ecs_test.go
pkg/logging/standardoutput/standard_output_logger.go
pkg/logging/standardoutput/standard_output_logger_test.go

This PR adds the following
- a convenient assert method to assert expected logged messages in testing
- a standard logger that wraps dispatcher and makes logging more readable
- as a side-effect the ecs.Error struct renamed to ecs.Err to avoid conflicts with the standardlogger.Error function introduced
Make logging even easier
UTs

add the soteria logging wrarppers,utils and assertions

---

pkg/api/client_runtime.go
pkg/api/client_runtime_test.go

Changes the `CloudClientRuntime` to use the region interpolated path on
deployment notes commands
#46 
Deployment notes do not work with a regionless path.
Manually

api: /deployment/{id}/notes should use region path

---

.github/workflows/go.yml

Adds the cache action to all workflows so that the Go modules can be
pre-cached
Cached dependencies to speed up the builds

build: Add Go module cache for GitHub actions

---

pkg/util/cmdutil/close.go
pkg/util/cmdutil/close_test.go

In order to be able to log close resource error, I made this helper. It will be used to handle Vault connection close errors.
- https://github.com/elastic/soteria/pull/676

feat(cmdutil): add resource closer logger.

---

pkg/api/api.go
pkg/api/config.go
pkg/api/http_transport.go
pkg/api/transport_user_agent.go
pkg/api/transport_user_agent_test.go

Adds a new type `UserAgentTransport` which wraps an `http.RoundTripper`
modifying all of the requests that pass through the Transport and
setting the user agent either to the default value if not set, or to the
value that has been configured.
Adds a `UserAgent` property to `api.Config` so that it's easily
configurable for users using our SDK.
Resolves #75 
Manually and mocking ecctl:
```console
$ dev-cli deployment list --verbose
Using config file: /Users/marc/.ecctl/config.json
==================== Start of Request #0 ====================
POST /api/v1/users/auth/_login HTTP/1.1
Host: XXXX:12343
User-Agent: cloud-sdk-go/2.5.0
Content-Length: 78
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip
[...]
```

api: Add custom User-Agent transport

---

pkg/api/transport_errcatch.go
pkg/api/transport_errcatch_test.go

Modifies the `ErrCatchTransport` type so that it handles the case when
`Content-Type` is `text/html`, the auto-generated client framework won't
be able to handle the proxied responses of that type since they're
contingent on the error response specified by the swagger definition,
thus anything with a `Content-Type` different than `application/json`
won't be handled and instead a cryptic error will be returned.
Any responses returned by the proxy and not by the actual Public API
which differ to the swagger definition, won't be handled properly and a cryptic
error is returned.
```console
$ ecctl --config ess --region  us-east-1 platform deployment-template show aws-io-optimized
&{[]} (*models.BasicFailedReply) is not supported by the TextConsumer, can be resolved by supporting …
```

api: Modify transport to handle Proxied responses

---

pkg/multierror/doc.go
pkg/multierror/examples_test.go
pkg/multierror/prefixed.go
pkg/multierror/prefixed_example_test.go
pkg/multierror/prefixed_test.go

Adds a new package under `pkg/multierror` which is aimed to be used
instead of `multierror.Error`. The main motivation behind this change is
to enforce a prefix to be used in all of the multierrors which will
provide more context to the error consumers.
It features multierror unpacking to keep all the errors same level and
in case the wrapped errors are also a Prefixed type, a prefix will be
added to each of the single errors to add that additional context to it.
Have more context in our errors.
With unit tests, as an example: 
```go
// code:
func (c *Config) Validate() error {
var err = multierror.NewPrefixed("api config validation")
if c.Client == nil {
err = err.Append(errors.New("client cannot be empty"))
}
if c.AuthWriter == nil {
err = err.Append(errEmptyAuthWriter)
}
err = …
```

multierror: Add package with Prefixed error type

---

go.mod
go.sum

Reverts the multierror dependency to 1.0.0 as it requires Go1.14 and can cause problems since we are still on Go1.13.
Also ran go mod tidy

deps: revert multierror to 1.0.0

---

go.mod
pkg/util/cmdutil/flag.go
pkg/util/cmdutil/flag_test.go

Adds a new `DecodeFlags` function which through reflection and
`mapstructure` is able to decode a cobra.Command defined flags into a
structure's fields which match the flag's type and mapstructure tag.
By using this function we can greatly reduce the flag-parsing code and
offload most if not all of the flag parsing by using this function.
Projects which use the cobra framework to parse flags and populate a
structure can use this function and reduce all of boilerplate code which
doesn't add any value.
By using it in ecctl. An example on how much code can be deleted:
```diff
diff --git a/cmd/deployment/show.go b/cmd/deployment/show.go
index f3ad90d..56f2f93 100644
--- a/cmd/deployment/show.go
+++ b/cmd/deployment/show.go
@@ -25,7 +25,6 @@ import (
cmdutil "github.com/elastic/ecctl/cmd/util" …
```

cmdutil: Add DecodeFlags to reduce parsing code

---

go.sum
pkg/api/api.go
pkg/api/api_test.go
pkg/api/apierror/unwrap.go
pkg/api/apierror/unwrap_multierror.go
pkg/api/apierror/unwrap_test.go
pkg/api/config.go
pkg/api/config_test.go
pkg/api/login_user.go
pkg/api/login_user_test.go
pkg/api/mock/error.go
pkg/api/mock/error_test.go
pkg/api/mock/errors.go
pkg/api/mock/errors_test.go
pkg/auth/new_authwriter.go
pkg/auth/new_authwriter_test.go
pkg/auth/user_login.go
pkg/auth/user_login_test.go
pkg/multierror/prefixed.go
pkg/multierror/prefixed_test.go

This patch contains a few changes aimed to making the SDK friendlier for
consumers, moving logic from external calls to implicit calls on the
API constructing function, controling the behavior through a bool flag
which still allows control over it when desired.
There's multierror changes which have been done to move over from the
multierror package owned from Hashicorp to our own. This wasn't entirely
needed for this patch but it makes the errors and wrapping of errors
that much nicer that it adds good value.
Also Moves the `UnwrapError` function from the `api` package to an
`apierror` subpackage and renaming the function to `Unwrap` this is due
to an import cyclic issue where `api` imports the `auth` package and in
order to be able to unwrap the errors returned in the `auth` package …

api: Move LoginUser from ecctl codebase

---

pkg/plan/planutil/track.go
pkg/plan/planutil/track_test.go
pkg/plan/stream.go
pkg/plan/track_change_params.go
pkg/plan/track_change_test.go

This change removes all the instances of hashicorp's multierror in favor
of our own multierror package.
Use prefixed multierrors.

plan: Use local multierror.Prefixed as multierror

---

pkg/api/api_test.go
pkg/api/config.go
pkg/api/deploymentapi/deploymentsize/sizes.go
pkg/api/deploymentapi/deploymentsize/sizes_test.go
pkg/api/deploymentapi/request_id.go
pkg/api/deploymentapi/request_id_test.go
pkg/api/ess.go

This changes the constructor behavior of `NewAPI` and the `Config`
validation now only accepts an `auth.APIKey` or `*auth.APIKey` as the
only valid AuthWriter's for the API when the host is set to the ESS host
(`https://api.elastic-cloud.com`). Also adds a constant: `ESSEndpoint`.
Additionally, adds a new function to the `deploymentapi` package:
`deploymentapi.RequestID`, which will always return a request ID to be
used in `deploymentapi.CreateParams`. It will either return an auto-
generated string of 64 characters or the string argument which is passed
to the function.
Last, it adds a new package called `deploymentsize` and a new function:
`Parse` which will parse a string in the format of `<size><unit`, valid
examples of parseable sizes are:
* Gigabyte: `10g`, `0.5G`, `16gb`.
* …

api: Add better API defaults and helpers

---

pkg/util/ec/rand.go

This patchs fixes a bug where the random strings generated the random
string functions in the `ec` package weren't seeded so the randomized
strings returned were pretty consistent and not random.
* `ec.RandomResourceID()`
* `ec.RandomResourceLength(<length>)`
Random functions should generate random data!
Adding some unit tests.

ec: Seed random so randoms actually are random

---

pkg/api/http_transport.go
pkg/api/http_transport_test.go

This patch adds the case where a UserAgentTransport is passed to the
function. Previously, it was writing an error to the ErrorDevice.
Fixes a small "bug" where an error is printed out.

api: Fix transport error on UserAgentTransport

---

pkg/api/deploymentapi/create.go
pkg/api/deploymentapi/update.go

This patch modifies the Update function parameters to allow the consumer
to specify a PayloadOverrides which can be used to override nested
values in the resources. Currently supports Version, Name and Region.
This allows upgrading all of the deployment's resources using a centralized version.

deploymentapi: Allow overrides on Update operation

---

go.mod
go.sum
pkg/api/http_transport.go

This patch removes the todo comment on the http.Transport constructor to
use the built-in `.Clone()` method introduced in Go 1.13. It also bumps
the required Go version in go.mod to `1.13`.
Use built-in Clone rather than a copy of the http.DefaultTransport settings.

api: Use http.Transport.Clone() for new transports

---

go.mod
pkg/api/mock/client.go
pkg/api/mock/client_test.go
pkg/api/mock/request.go
pkg/api/mock/request_test.go
pkg/api/mock/response.go

This patch adds the ability to assert certain *http.Request fields which
are sent to the http.RoundTripper on any of the request / reply flows
which are tested and asserted in our unit tests.
Adds the ability to assert what's sent over to the API so our unit tests
become more complete. Since it's an optional field, it doesn't enforce
that field to be set in the `mock.Response`, but rather make it optional
for those tests where it makes sense to do so.
Ability to assert outgoing http.Request sent by the SDK.
Via unit tests

mock: Add ability to assert received *http.Request

---

go.sum
pkg/api/client_runtime.go
pkg/api/client_runtime_test.go

Adds a conditional which checks that if the set raw metadata endpoint is
called, then the producer is substituted from JSON to Text in order to
be able to send a string as a JSON object without escaping the quotes.
Handle the set-Elasticsearch raw metadata operation natively
With unit tests and tested mocking the SDK.

api: transport now handles raw metadata producer

---

pkg/api/deploymentapi/resync_test.go
pkg/api/mock.go
pkg/auth/testutil.go

Changes the way that `api.NewMock` creates the *API struct. Instead of
creating the API struct directly, it uses the constructor api.NewAPI so
all our tests can replicate more closely what is run on in real life.
This patch will cause any unit test which assert any API path error to
fail, since it changes the basepath to `mock.elastic.co` and uses the
suffix `/api/v1` instead of a bogus one.
Having better unit tests.
Via our unit tests.

api: NewMock now uses NewAPI as the constructor

---

pkg/api/deploymentapi/deploymentsize/sizes.go
pkg/api/deploymentapi/deploymentsize/sizes_test.go

Changes the Parse code to only be able to parse the Gigabyte notation
with 0.5g increments allowed, meaning that only 0.5, 1gb, 1.5gb, etc are
accepted.

deploymentsize: change Parse to only accept g

---

go.sum
pkg/api/config.go
pkg/api/debug.go
pkg/api/debug_test.go
pkg/api/http_transport.go

Adds a new configuration parameter `RedactAuth` to `api.VerboseSettings`
which if set, will replace the contents of the `Authorization` header
with [REDACTED].
The default behavior still preserves the original contents of the
header.
Resolves #110

api: Add RedactAuth bool option to VerboseSettings

---

go.sum
pkg/util/ec/region.go
pkg/util/ec/region_test.go

Adds a new RequireRegionSet(), taking a region string and ensuring
the contents of it aren't empty or spaces, returning an error if so.
Part of #129

ec: Add RequireRegionSet ensuring a region is set

---

pkg/api/mock.go

Exports three new variables:
* DefaultWriteMockHeaders
* DefaultReadMockHeaders
* DefaultMockHost
Part of #129 
Easier request assertions.

api: Export default mock headers and host

---

pkg/api/mock/response.go
pkg/api/mock/response_test.go
pkg/api/platformapi/roleapi/add_blessing.go
pkg/api/platformapi/roleapi/add_blessing_test.go
pkg/api/platformapi/roleapi/create.go
pkg/api/platformapi/roleapi/create_test.go
pkg/api/platformapi/roleapi/delete.go
pkg/api/platformapi/roleapi/delete_test.go
pkg/api/platformapi/roleapi/list.go
pkg/api/platformapi/roleapi/list_test.go
pkg/api/platformapi/roleapi/set_blessing.go
pkg/api/platformapi/roleapi/set_blessing_test.go
pkg/api/platformapi/roleapi/show.go
pkg/api/platformapi/roleapi/show_test.go
pkg/api/platformapi/roleapi/update.go
pkg/api/platformapi/roleapi/update_test.go

This patch modifies all the roleapi public functions to have a
Region string required parameter which is then used to create a new
context.Context: api.WithRegion(context.Background(), params.Region)
and pass it as the API operation context.
Unit tests have been modified to include a request
assertion which ensures that the region path interpolation is used when
the /platform APIs are being called.
Additionally, a few new helper functions have been added that create a new response with request assertion and a statuscode.
Related: #129 
unit tests in ecctl

roleapi: Add Region field and WithRegion ctx

---

pkg/api/platformapi/allocatorapi/vacate.go
pkg/api/platformapi/allocatorapi/vacate_full_test.go
pkg/api/platformapi/allocatorapi/vacate_params.go
pkg/api/platformapi/allocatorapi/vacate_params_test.go
pkg/api/platformapi/allocatorapi/vacate_responses_test.go
pkg/api/platformapi/allocatorapi/vacate_test.go
pkg/plan/mock/generator.go
pkg/plan/mock/generator_test.go
pkg/plan/track_change_test.go
pkg/plan/track_response.go
pkg/plan/track_response_builder.go
pkg/util/kinds.go

Adds support for the `enterprise_search` kind to be vacated on allocator
vacates and adds support for the deployment plan change tracker too.
It doesn't refactor any of existing code and just builds on top of it.
Resolves #132

allocator vacate: Add enterprise search support

---

pkg/api/http_transport.go
pkg/api/http_transport_test.go

Adds another entry to `api.NewTransport` which handles mock.RoundTripper
and returns it wrapped in a UserAgent RoundTripper.
It's meant to improve testing.
When testing the `ecctl/pkg/cmd` layer, it'll always print `http transport warning: failed converting *mock.RoundTripper to *http.Transport` unless this patch is merged.
via `ecctl`

api: Add mock.RoundTripper to transport workflow

---

pkg/api/deploymentapi/depresourceapi/apm.go
pkg/api/deploymentapi/depresourceapi/appsearch.go
pkg/api/deploymentapi/depresourceapi/elasticsearch.go
pkg/api/deploymentapi/depresourceapi/kibana.go
pkg/api/platformapi/configurationtemplateapi/delete_test.go
pkg/api/platformapi/configurationtemplateapi/get.go
pkg/api/platformapi/configurationtemplateapi/get_test.go
pkg/api/platformapi/configurationtemplateapi/list.go
pkg/api/platformapi/configurationtemplateapi/list_test.go
pkg/api/platformapi/configurationtemplateapi/pull.go
pkg/api/platformapi/configurationtemplateapi/pull_test.go

This patch adds a new required `Format` field to the `GetTemplateParams`, `ListTemplatesParams` and `PullToFolderParams` structs.
This will allow the use of the `WithFormat()` method, in order to specify which inofrmation is populated in the response.
If "cluster" is specified, cluster_template is pupulated in the response. If deployment is specified, deployment_template is populated in the response.
Closes: https://github.com/elastic/cloud-sdk-go/issues/159
Preparation for using the new deployment template endpoint which uses the `deployment` format
Unit tests, and manually by testing with ecctl

configurationtemplateapi: Add Format field

---

CONTRIBUTING.md
developer_docs/STYLEGUIDE.md

Adds a styleguide that is specific to cloud-sdk-go instead of repurposing 
the one in ecctl.
Related: https://github.com/elastic/ecctl/issues/335
It can be confusing to have information that is not applicable to the project, 
so it makes sense that each project has its own styleguide.

docs: Add cloud-sdk-go specific styleguide

---

pkg/api/deploymentapi/depresourceapi/apm_test.go
pkg/api/deploymentapi/depresourceapi/appsearch_test.go
pkg/api/deploymentapi/depresourceapi/elasticsearch_parser.go
pkg/api/deploymentapi/depresourceapi/elasticsearch_parser_test.go
pkg/api/deploymentapi/depresourceapi/enterprise_search_test.go
pkg/api/deploymentapi/depresourceapi/kibana_test.go
pkg/api/deploymentapi/depresourceapi/new_payload.go
pkg/api/deploymentapi/depresourceapi/new_payload_test.go
pkg/api/deploymentapi/depresourceapi/new_stateless.go
pkg/api/deploymentapi/deptemplateapi/get.go
pkg/api/deploymentapi/deptemplateapi/get_test.go

Adds a workaround for a missing API so that the deployment templates can
be obtained on ESS by using the `deploymenttemplateapi.List()` method
with a filter function that returns an error when the template is not
found.
The behavior is controlled with a boolean `AsList` in `GetParams` and
a bool named `DeploymentTemplateAsList` on the `NewPayloadParams`.
This boolean should be removed as soon as the GET endpoint for a single
deployment template is available on ESS.
elastic/ecctl#335
unit tested thoroughly and manually tested in `ecctl`.

deploymentapi: Support List and filter templates

---

pkg/api/deploymentapi/depresourceapi/elasticsearch_parser_test.go
pkg/api/deploymentapi/depresourceapi/elasticsearch_test.go
pkg/api/deploymentapi/depresourceapi/elasticsearch_topology.go
pkg/api/deploymentapi/depresourceapi/elasticsearch_topology_test.go

In order to make things simpler for our users, this patch changes the
'Name' field in ElasticsearchTopologyElement for 'NodeType'
https://github.com/elastic/ecctl/issues/335
UX
Unit tests and manually by faking the SDK in ecctl

depresourceapi: Change the 'Name' field in ElasticsearchTopologyElement for 'NodeType'

---

pkg/api/deploymentapi/deploymentsize/sizes.go
pkg/api/deploymentapi/deploymentsize/sizes_test.go

Fixes a bug where defining memory size in capital letters failed with 
a misleading error.
For example: If `"4G"` was passed, the error would be
`strconv.ParseFloat: parsing "4g": invalid syntax`.
The function now accepts capitalised letters as well.
bug fix and UX
Manually by faking the SDK in ecctl and unit tests.

deploymentsize: Fixes a bug in ParseGb()

---

pkg/api/deploymentapi/trafficfilterapi/create.go
pkg/api/deploymentapi/trafficfilterapi/create_association.go
pkg/api/deploymentapi/trafficfilterapi/create_association_test.go
pkg/api/deploymentapi/trafficfilterapi/create_test.go
pkg/api/deploymentapi/trafficfilterapi/delete.go
pkg/api/deploymentapi/trafficfilterapi/delete_association.go
pkg/api/deploymentapi/trafficfilterapi/delete_association_test.go
pkg/api/deploymentapi/trafficfilterapi/delete_test.go
pkg/api/deploymentapi/trafficfilterapi/get.go
pkg/api/deploymentapi/trafficfilterapi/get_test.go
pkg/api/deploymentapi/trafficfilterapi/list.go
pkg/api/deploymentapi/trafficfilterapi/list_test.go
pkg/api/deploymentapi/trafficfilterapi/update.go
pkg/api/deploymentapi/trafficfilterapi/update_test.go

Adds an implementation for the traffic filtering APIs so they can be
leveraged in the terraform provider
Depends on #203

trafficfilterapi: Add CRUD and association APIs

---

pkg/api/apierror/json.go
pkg/api/platformapi/allocatorapi/vacate.go
pkg/api/platformapi/allocatorapi/vacate_error.go
pkg/api/platformapi/allocatorapi/vacate_full_test.go
pkg/api/platformapi/allocatorapi/vacate_responses_test.go
pkg/api/platformapi/allocatorapi/vacate_test.go
pkg/multierror/format.go
pkg/multierror/format_test.go
pkg/multierror/prefixed.go
pkg/multierror/prefixed_test.go
pkg/multierror/testdata/multierror.json
pkg/plan/planutil/track.go
pkg/plan/planutil/track_test.go
pkg/plan/planutil/wait_test.go
pkg/plan/stream.go
pkg/plan/stream_format.go
pkg/plan/stream_test.go
pkg/plan/track_response.go

Introduces a series of changes which allow the `allocator.Vacate()` to
return a multierror which can serialize the errors to JSON format.
To do so, multiple changes have been made throughout multiple packages,
providing building blocks for other APIs to leverage these, or use on-
demand.
`multierror.WithFormat()`: modifies a `multierror.Prefixed` or hashicorp
`multierror.Error` format functions which instead of formatting with a
"text" format, return a JSON formatted string.
`apierror.JSONError{}`: wrapping any `string` with this type, will make
it compatible to `json.Marshal`-ed. A `apierror.NewJSONError()` func is
provided for convenience too, allowing errors to be wrapped in the type.
`plan.StreamJSON`: has been fixed to return the final `error` result in
JSON formatted form.
`plan`: …

error: Add JSON formatted errors for vacate APIs

---

pkg/api/platformapi/allocatorapi/list.go
pkg/api/platformapi/allocatorapi/list_test.go

Adds a new `Size` parameter to `ListParams` which allows users to obtain
more than the default `100` allocator size.
With the current implementation, it is impossible to obtain more than 100 allocators for a region. This shouldn't be the case.
Unit tested.

allocatorapi: Add Size parameter to ListParams

---

pkg/api/deploymentapi/get.go
pkg/api/deploymentapi/get_test.go

Adds a new optional boolean to `deploymentapi.Get()` which allows users
to optionally convert the legacy plan format to the current format.
Add the option to convert pre-2.x ECE plans

deploymentapi: Add ConvertLegacyPlans to Get

---

.github/workflows/go.yml
internal/cmd/apivalidator/requests/run_test.go
pkg/api/platformapi/allocatorapi/vacate_test.go

We've been on go `1.13` for a while and go 1.15 is out and has many
advantages over go `1.15`. This patch updates to the new version and
fixes the tests which are broken as part of the upgrade
Live in the present!

go: Update to go 1.15

---

.golangci.yml
pkg/sync/pool/pool.go
pkg/sync/pool/pool_examples_test.go
pkg/sync/pool/pool_params.go
pkg/sync/pool/pool_test.go

This patch adds a new `FailFast` parameter to `pool.Params` which allows
consumers to toggle a new pool behavior where the pool will gracefully
stop when one of the workers returns with an error. This will stop
processing any additional work but try to continue processing the work
that's in-flight or cancel the execution when the `params.Timeout.Stop`
`time.Duration` is exceeded.
Provide more features for the deployer.

sync/pool: Add FailFast parameter, stopping on err

---

.github/workflows/apivalidation.yml
CONTRIBUTING.md
build/Makefile.apivalidation
build/Makefile.deps
build/Makefile.swagger
build/apivalidation/apivalidation_test.go

Adds a new GH actions workflow to run the api-validation tests once 
a day.
Additionally, I have removed the api-validation tests on each 
`make swagger` as now we don't necessarily have the apidocs
on par with what's on production. We may have some endpoints 
that are not publicly available yet for development purposes, so 
there's no point in having these as they are likely to fail on occasion.
Running the make targets locally

actions: Add scheduled api-validation job

---

.github/workflows/apivalidation.yml

This PR attempts to fix the broken validation tests. This same workflow 
works fine on an internal project using go 1.13, let's try 1.14 and see if it
works.
Additionally I have removed a couple of env vars from the workflow as
they are not needed.
**Note** I have go 1.15 on my machine and the tests work just fine, 
must be a Github thing?

apivalidation: Set workflow to Go 1.14

---

pkg/api/platformapi/allocatorapi/vacate.go
pkg/api/platformapi/allocatorapi/vacate_full_test.go
pkg/multierror/prefixed.go
pkg/plan/stream.go
pkg/plan/stream_test.go

This patch fixes the returned error format when an allocatorapi.Vacate
returns with an error.
The problem wasn't on how the errors are marshalled when OutputFormat,
but on the `multierror.Prefixed` error and the unpacking that it does.
As it turns out, because the prefix from the error from `plan.Stream()`
isn't equal to the the multi error where it is flattened to through the
`merr.Append()` (`unpackErrors()`), as it was being squashed by calling
`fmt.Sprint(prefixed.Prefix, ": ", errElement.Error()),`. Already, this
isn't ideal and probably we might want to look more closely at using the
error wrapping `fmt.Errorf("%s: %w")`, and its implications.
Invalid JSON (multi)error formatting.

allocatorapi: Fix incorrect json error formatting

---

pkg/api/apierror/unwrap.go
pkg/api/transport_custom.go

Two patches to be able to still be able to unwrap the error.
`failed reading error body` is not a great error.

transport: Adds another patch to unwrap the error

---

go.sum
pkg/api/deploymentapi/esremoteclustersapi/get.go
pkg/api/deploymentapi/esremoteclustersapi/get_test.go
pkg/api/deploymentapi/esremoteclustersapi/update.go
pkg/api/deploymentapi/esremoteclustersapi/update_test.go

This patch adds both `Get()` and `Update()` functions for the remote
clusters APIs which power ESS Cross Cluster Search assignments.
Part of elastic/terraform-provider-ec#137
Add the `remote-clusters` APIs to the SDK.

esremoteclustersapi: Add Get and Update functions

---

pkg/api/transport_custom.go
pkg/api/transport_custom_test.go

Fixes a severe bug where the `*http.Response` and / or `error` from the
custom `http.RoundTripper` implementation were lost very often, causing
any clients with `retries > 0` to miss-behave, causing some http calls
to never return.
I've added a few tests to ensure this doesn't happen again and tested
very thoroughly with the terraform provider with both retries enabled,
and disabled.
Introduced by #220
Terraform provider, with Retries from 0 to 4.

transport: Fix retries logic when enabled

---

pkg/api/transport_custom.go
pkg/api/transport_custom_test.go

Modifies the error assertion on the custom `http.RoundTripper` to use
`net.Error` instead of the struct type `context.DeadlineExceeded`. This
allows the client retries to be performed un many more timeouts (net,
http, or sdk framework).
Retry on any timeout.

http: Retry on net.Error.Timeout() == true

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/transport_custom.go

This patch takes into consideration all the Timeout values used on all
layers of the sdk, this means that we have to account for in order from
a nested view:
- `runtime.ClientTransport`: The auto-generated client transport has its
own configurable timeout (per operation), which will also cancel any
outgoing requests if the timeout is exceeded. When individual client
requests do not include a Timeout configured, a default variable is
used: `runtimeclient.DefaultTimeout`, which is why we're  modifying
its value.
- `http.Client.Timeout`: Within the `http.Client` The timeout includes
connection time, any redirects, and reading the response body.
- `net.Dialer.Timeout`: Within the `http.RoundTripper` implementation,
this is the timeout that is used on a per-request basis.
Taking all the above …

api: Correct all timeout values for retries

---

go.sum
pkg/api/deploymentapi/depresourceapi/new_payload.go
pkg/api/deploymentapi/depresourceapi/new_payload_test.go
pkg/api/deploymentapi/deptemplateapi/get.go
pkg/api/deploymentapi/deptemplateapi/get_test.go

As the bug with the GET deployments/template/{template_id} endpoint
has been fixed, we no longer need to use the `AsList` field when calling it.
Stay updated!
Manually by faking the SDK in ecctl and the TF provider

deptemplateapi: Remove workaround for the deployment template get API

---

pkg/api/deploymentapi/migrate.go
pkg/api/deploymentapi/migrate_test.go

Adds a new `Migrate` API to the `deploymentapi` package.
This new API returns a deployment update request that would 
transform this deployment from its template to the provided one.
Part of https://github.com/elastic/terraform-provider-ec/issues/157

deploymentapi: New Migrate API for the deployment migrate endpoint

---

pkg/util/ec/types.go
pkg/util/ec/types_test.go

Adds a function to create an int pointer from an int
Required by https://github.com/elastic/cloud-cli/issues/1271
During container set migration from v0 to v1 we need to create a pointer from an int

adds a function to create an int pointer from an int

---

go.sum
pkg/api/deploymentapi/testdata/observability_get.json
pkg/api/deploymentapi/update_payload.go
pkg/api/deploymentapi/update_payload_test.go

Fixes an issue where when generating a `DeploymentUpdateRequest` an 
empty `size` within a cluster topology element would cause a panic.
Part of: https://github.com/elastic/ecctl/issues/413
Unit tests

deploymentapi: Fix update payload

---

pkg/api/deploymentapi/testdata/logging_metrics_legacy_kibana_get.json
pkg/api/deploymentapi/testdata/logging_metrics_legacy_kibana_update.json
pkg/api/deploymentapi/testdata/observability_get.json
pkg/api/deploymentapi/testdata/observability_update.json
pkg/api/deploymentapi/update_payload.go
pkg/api/deploymentapi/update_payload_test.go

Adds a fix where topology elements with `memory_per_node` set instead of
the new `size.value` field would cause a panic. It adds two unit tests
one per each legacy Cluster type payload to assert that no panics are
returned.
Addresses elastic/ecctl#421

deploymentapi: Parse memory_per_node as well

---

pkg/api/deploymentapi/extensionapi/create.go
pkg/api/deploymentapi/extensionapi/create_test.go
pkg/api/deploymentapi/extensionapi/delete.go
pkg/api/deploymentapi/extensionapi/delete_test.go
pkg/api/deploymentapi/extensionapi/get.go
pkg/api/deploymentapi/extensionapi/get_test.go
pkg/api/deploymentapi/extensionapi/list.go
pkg/api/deploymentapi/extensionapi/list_test.go
pkg/api/deploymentapi/extensionapi/update.go
pkg/api/deploymentapi/extensionapi/update_test.go

New APIs for all deployment extension CRUD APIs
Related: https://github.com/elastic/terraform-provider-ec/pull/216

deploymentapi: Add new CRUD APIs for extensions

---

pkg/api/platformapi/allocatorapi/search_test.go
pkg/multierror/prefixed.go
pkg/multierror/prefixed_test.go

This PR adds both concurrency support for the `Prefixed` structure and
sorts to the `Errors` prior to `Error()` output.
Use the multierror.Prefixed concurrently and assert the error output.

multierror: Make concurrently safe and sort errors

---

pkg/api/platformapi/allocatorapi/vacate_full_test.go
pkg/plan/track_step.go
pkg/plan/track_step_test.go

Updates the plan tracker behavior to only return errors when the last
step plan log `plan-completed` has `"status": "error"`.
A more resilient plan tracker.

plan tracker: Update failure modes

---

go.mod
go.sum
pkg/api/platformapi/allocatorapi/vacate_full_test.go
pkg/plan/track_change.go
pkg/plan/track_change_test.go

Patches the plan tracker so it catches plans that failed but finished
before the plan tracker had the chance to call the API, resulting in
the `changedResources` slice that is used in the plan tracker to filter
out unrelated changes to be of length 0.
When `changedResources` is empty it means that when the plan tracking
goroutine checked the pending plan, there were no pending plans on any
of the deployment resources, since some of the resources might have had
some changes, we're effectively sending a message to the plan tracker
channel when the current plan's `plan-completed` step has an error.
Fix the edge case where a deployment's pending plan might have finished before the plan tracker had any chance to inspect it.
The edge case is admittedly a very small % of deployments that might …

plan tracker: fix missed plan error on fast plan completion

---

pkg/api/commentapi/list.go
pkg/api/commentapi/list_params.go
pkg/api/commentapi/list_params_test.go
pkg/api/commentapi/list_test.go

Introduces a new operation to list all comment of a given resource. 
Required by https://github.com/elastic/ecctl/issues/456
Unit tested and via `ecctl` - PR will follow

implement comment list operation

---

pkg/api/commentapi/delete.go
pkg/api/commentapi/delete_params.go
pkg/api/commentapi/delete_params_test.go
pkg/api/commentapi/delete_test.go

Introduces a new operation to delete a specific comment of a given resource. 
Required by https://github.com/elastic/ecctl/issues/456
Unit tested and via `ecctl` - PR will follow

implement comment delete operation

---

pkg/api/commentapi/create_params.go
pkg/api/commentapi/create_params_test.go
pkg/api/commentapi/create_test.go

Aligns the validation error messages with the ones used in the other comment operations ( list and show so far )

align create comment operation validation messages

---

pkg/api/deploymentapi/trafficfilterapi/create_association.go
pkg/api/deploymentapi/trafficfilterapi/create_association_test.go
pkg/api/deploymentapi/trafficfilterapi/delete_association.go
pkg/api/deploymentapi/trafficfilterapi/delete_association_test.go

Fixes a bug in the validation for traffic filter association APIs where `params.ID` 
was being validated twice instead of `params.EntityType`.

trafficfilterapi: Fix bug in validation

---

pkg/api/deploymentapi/create.go
pkg/api/deploymentapi/override_settings.go
pkg/api/deploymentapi/override_settings_test.go
pkg/api/deploymentapi/update.go

Adds a new public function `OverrideCreateOrUpdateRequest` which allows
setting certain overrides on the Deployment requests in the Create and
Update operations.
The function was private before making it part of the Create and Update
calls. This wasn't always desirable specially when pairing it with the
`--generate-payload` flag in `ecctl` where it wouldn't return the fields
that were overridden.
The function has been expanded to:
- Set overrides to all the application `ref_id` fields.
- ElasticsearchRefID overrides.
- Plugin overrides.
- Selection between node_roles and node_types when both are set.

deploymentapi: Add OverrideCreateOrUpdateRequest

---

pkg/api/deploymentapi/extensionapi/update.go
pkg/api/deploymentapi/extensionapi/update_payload.go
pkg/api/deploymentapi/extensionapi/update_payload_test.go

Adds new functionality to build an update request form get in order to be
able to generate an update payload in ecctl. https://github.com/elastic/ecctl/pull/477
unit tests and by running ecctl manually

extensionapi: Functionality to build an update request form get

---

cmd/generator/cloudspec/spec_modifier.go
go.sum
pkg/models/deployment_template_info_v2.go
pkg/models/deployment_template_request_body.go

This PR hacks the new deployment template models' `order` field to handle the `0` value 
which is ignored if the field is not nullable. 
We have done the same in the old models and we missed the new ones.
When we are doing a `pull` all deployment templates that have order=0, are written as json files without this attribute.
This is caused by the `json` library which, during structure marshaling it ignores any int attributes with value = 0 ( because golang assumes this is the default value of all int )

client: handle empty deployment template order fields in client generation

---

pkg/api/deploymentapi/deploymentsize/sizes.go
pkg/api/deploymentapi/deploymentsize/sizes_test.go

Allows the `deploymentsize.ParseGb` to parse `0` and `0g`.
Allow parsing autoscaling sizes, related to https://github.com/elastic/terraform-provider-ec/issues/258

deploymentsize: Allow ParseGb to parse 0 sizes

---

cmd/generator/cloudspec/spec_modifier.go
pkg/client/platform_infrastructure/update_proxies_settings_parameters.go
pkg/models/proxies_settings.go

This address the well-known issue the PATCH methods provided by the admin-console API
The definition requires that the PATCH method accepts a `string` and not a structured `model`
This makes the generated go-client to send a string request body and not a json request body.
This PR does the following :
1. Hacks the swagger generation process to accept a `ProxiesSettings` structured model instead of a string
2. Removes all required fields from the structured model `ProxiesSettings`. If we don't remove them then json marshaling will add them with null values in the generated json body and this will cause the API to fail.
Required by https://github.com/elastic/ecctl/issues/484 and https://github.com/elastic/ecctl/issues/483
Support Patch API request against the proxies settings API
via …

client: handle empty settings patch API operation in swagger client generation

---

pkg/api/platformapi/proxyapi/settingsapi/get.go
pkg/api/platformapi/proxyapi/settingsapi/get_test.go

Implements the operation of `get proxies settings` as defined [here](https://www.elastic.co/guide/en/cloud-enterprise/current/get-proxies-settings.html)
https://github.com/elastic/ecctl/issues/484

implement get proxies settings operation

---

pkg/api/platformapi/proxyapi/settingsapi/update.go
pkg/api/platformapi/proxyapi/settingsapi/update_test.go

Implements the operation of `set proxies settings` as defined [here](https://www.elastic.co/guide/en/cloud-enterprise/current/set-proxies-settings.html)
https://github.com/elastic/ecctl/issues/484

implements proxies settings update operation

---

pkg/api/platformapi/proxyapi/settingsapi/patch.go
pkg/api/platformapi/proxyapi/settingsapi/patch_test.go

Implements the operation of `update proxies settings` as defined [here](https://www.elastic.co/guide/en/cloud-enterprise/current/update-proxies-settings.html)
https://github.com/elastic/ecctl/issues/484
Depending on https://github.com/elastic/cloud-sdk-go/pull/327

implements proxies settings patch operation

---

pkg/api/platformapi/allocatorapi/vacate.go
pkg/api/platformapi/allocatorapi/vacate_params.go
pkg/api/platformapi/allocatorapi/vacate_params_test.go
pkg/api/platformapi/allocatorapi/vacate_responses_test.go
pkg/api/platformapi/allocatorapi/vacate_test.go

When vacating some packed allocators, it sometimes fails to start to vacate allocators because of time out when calling adminconsole API.
I found that when the vacate logic prepare cluster's plan to apply to each cluster, it is hitting adminconsole API a lot of times.
And the response of every call to the API have every plan of every cluster in an allocator.
When actual calling actual vacate API, it only uses the cluster's own calculated plan data and do not use others'.
And I think I fix this behavior to call API to return only each cluster's plan.
Rel: https://github.com/elastic/cloud/issues/78915
Explained in the description section.
I tested the change running debugger but I did not make change in unit tests.

better way to call api to retrieve cluster plan when vacating allocators

---

build/Makefile.deps

Uses the built in `go install` that newer versions of Go have to install
the Go binary dependencies that this project relies on.

scripts: Use `go install` rather than gobin

---

build/Makefile.apivalidation
build/Makefile.deps

Removes the last references of the gobin binary. The "api-validation"
job failed overnight because it was still referencing a gobin target.
See https://github.com/elastic/cloud-sdk-go/runs/3376135556?check_suite_focus=true#step:5:107

deps: Remove last trace of gobin

---

.github/workflows/release.yml

Fixes the release flow when manually triggered, since it was not pulling
the tags from the remote, this caused the `versionbump` binary to fail
the tag check (`-c` option) and thus failed the build.

release: Describe the git tag on master

---

.github/workflows/changelog_generation.yml
NOTICE
build/Makefile.dev

This PR adds auto-generation of `NOTICE` file on every commit to `master`. Right now we are missing any automation around that.
Unfortunately, it can be tested only after merge.
Similar to https://github.com/elastic/terraform-provider-ec/pull/372

Enable auto-generated NOTICE on commit

---

pkg/api/mock/response.go
pkg/api/mock/response_test.go

It adds HTTP `409` response to Mock API client.
To be able to run acceptance tests in TF ElasticCloud provider, we need to mock API client and e.g. to check whether a [role already exists](https://github.com/elastic/cloud-sdk-go/blob/master/pkg/client/platform_infrastructure/delete_blueprinter_role_responses.go#L61-L62), we need to return that HTTP code.
---
Metas: https://github.com/elastic/cloud/issues/93118 https://github.com/elastic/cloud/issues/93122
Rel: https://github.com/elastic/cloud/issues/93121

Add 409 response to Mock API client

---

pkg/api/userapi/authapi/createkey.go
pkg/api/userapi/authapi/createkey_test.go

Adds the missing `api.API` validation in `CreateKeyParams.Validate()`.

userapi/authapi: Add API validation in CreateKey

---

pkg/api/mock/response.go
pkg/api/mock/response_test.go

It adds missing HTTP responses (`302`, `400`, `501`, `502`) to Mock API client.
To be able to run acceptance tests in TF ElasticCloud provider, we need to mock API client and some HTTP responses are missing.
---
Metas: https://github.com/elastic/cloud/issues/93118 https://github.com/elastic/cloud/issues/93122
Rel: https://github.com/elastic/cloud/issues/93121

Add missing responses to Mock API client

---

pkg/api/deploymentapi/testdata/apm_update.json
pkg/api/deploymentapi/testdata/appsearch_update.json
pkg/api/deploymentapi/testdata/enterprise_search_update.json
pkg/api/deploymentapi/testdata/logging_metrics_legacy_kibana_update.json
pkg/api/deploymentapi/testdata/observability_update.json
pkg/api/deploymentapi/update_payload.go

The response from the API does already contain all topologies, but they were removed when building the update request. Now we simply keep all elements as the API returns them.
This is mainly needed when autoscaling is enabled. In that case the update request must contain all existing topology elements to validate correctly.
Fixes an `ecctl` issue: https://github.com/elastic/ecctl/issues/596

Keep all Elasticsearch topologies when building update request.

---

pkg/api/client_runtime.go
pkg/api/client_runtime_test.go

Billing path should be region-less
I have just added `billing` to `globaPath` to return regionLess runtime.
I wanted to call `GetCostsItemsByDeployment` but I was getting the error
```
the requested operation requires a region but none has been set
```

fix(runtime): add billing to globalPath

---

pkg/api/platformapi/allocatorapi/vacate.go
pkg/api/platformapi/allocatorapi/vacate_responses_test.go
pkg/api/platformapi/allocatorapi/vacate_test.go

- The actual vacate request that was being used on cluster resources did not propagate down the flag being set for "VacateParams"
- This leads to a request that ultimately does not include the query param when performing the vacate
Unable to pass `--allocator-down true` and have it be respected from ecctl's perspective.
UTs and will validate with a local version of ecctl (**TODO**)

fix: support allocator down for vacating cluster resources

---

cmd/generator/cloudspec/spec_modifier.go
pkg/models/apm_topology_element.go
pkg/models/app_search_topology_element.go
pkg/models/elasticsearch_cluster_topology_element.go
pkg/models/enterprise_search_topology_element.go
pkg/models/integrations_server_topology_element.go
pkg/models/kibana_cluster_topology_element.go

This changes the type of the `instance_configuration_version` field to `*int32` for all topology elements and marks the fields as nullable.
Rel: https://elasticco.atlassian.net/browse/CP-5181
We can't set `instance_configuration_version` to `0` because it will be considered as an empty value and it will be omitted during JSON marshalling.

Handle empty instance_config_version in topology elements

---

.changelog/1.16.0/455.yml
NOTICE
notes/v1.16.0.md

- Added a changelog entry
- The NOTICE was outdated so I updated that as well.

Add changelog for #455

---

pkg/api/deploymentapi/update.go

cloud-sdk-go do not use  validate_only parameter for deployment update api, althouth ElasticCloud's REST API uses it.
So, this pull request addressed this issue.
reference: https://www.elastic.co/guide/en/cloud-enterprise/current/update-deployment.html#ece_query_parameters_13
https://github.com/elastic/cloud-sdk-go/issues/459
cloud-sdk-go do not use  validate_only parameter for deployment update api, althouth ElasticCloud's REST API uses it.
go 1.21.7
Apple M3 Pro 14.2.1
Local Go script 
With ValidateOnly = true parameter, rolling update is not started. 
replace package: https://github.com/kotaroooo0/poc-validate-only/blob/main/go.mod#L7
give ValidateOnly parameter: https://github.com/kotaroooo0/poc-validate-only/blob/main/main.go#L25

Add ValidateOnly params for deployment update API

---

pkg/api/platformapi/instanceconfigapi/get.go
pkg/api/platformapi/instanceconfigapi/get_test.go
pkg/api/platformapi/instanceconfigapi/list.go
pkg/api/platformapi/instanceconfigapi/list_test.go

Adds support for new parameters `show_deleted`, `show_max_zones` and `config_version` for `get` and `list`

instanceconfigapi: Implement additional parameters.

---

.github/workflows/release.yml

Due to security restrictions the workflow is not allowed to push directly to master and therefore will fail every time.
So I think it makes sense to just remove it and to update the VERSION manually.
Example action: https://github.com/elastic/cloud-sdk-go/actions/runs/9060730704/job/24891035927

Remove workflow updating master.

---

.changelog/1.20.0/472.yml
Makefile
NOTICE
notes/v1.20.0.md

Updates version, changelog and NOTICE for the next release 1.20.0

Prepare release 1.20.0

---

pkg/api/client_runtime.go
pkg/api/client_runtime_test.go

Updates the list of global APIs to include the /organizations endpoint.
Avoiding errors like: `the requested operation requires a region but none has been set`

Set organizations as global to skip region checks

---

pkg/api/client_runtime.go
pkg/api/client_runtime_test.go

Updates the list of global APIs to include the `/saas` endpoint.
https://elasticco.atlassian.net/browse/CP-7863
The `/saas/billing/prices` endpoint is a global endpoint that doesn't require the `/regions/$region` prefix. However, if this endpoint isn't added to the global list, trying to use it in the `cloud-cli` code without specifying a region in the context will result in this error `the requested operation requires a region but none has been set`.
Tested using the new `cloud-cli` changes from https://github.com/elastic/cloud-cli/pull/1525, which perform a `GET /saas/billing/prices` request.

Set `saas` endpoint as global to skip region checks

---

.changelog/1.21.0/477.yml
pkg/api/organizationapi/get.go
pkg/api/organizationapi/get_test.go
pkg/api/organizationapi/invitation_create.go
pkg/api/organizationapi/invitation_create_test.go
pkg/api/organizationapi/invitation_delete.go
pkg/api/organizationapi/invitation_delete_test.go
pkg/api/organizationapi/invitation_list.go
pkg/api/organizationapi/invitation_list_test.go
pkg/api/organizationapi/list.go
pkg/api/organizationapi/list_test.go
pkg/api/organizationapi/member_delete.go
pkg/api/organizationapi/member_delete_test.go
pkg/api/organizationapi/member_list.go
pkg/api/organizationapi/member_list_test.go
pkg/api/organizationapi/member_role_assignments_add.go
pkg/api/organizationapi/member_role_assignments_add_test.go
pkg/api/organizationapi/member_role_assignments_remove.go
pkg/api/organizationapi/member_role_assignments_remove_test.go
pkg/api/organizationapi/update.go
pkg/api/organizationapi/update_test.go

Adds the APIs for managing an Elastic cloud organization and its members.
- Get/List/Update organization
- List/Create/Delete organization invitations
- List/Delete organization members
- Add/Remove roles from a member
(https://www.elastic.co/guide/en/cloud/current/Organizations.html)
This change is needed to implement RBAC support in terraform-provider-ec

Implement organizations API.

---

Makefile
notes/v1.21.0.md

- Update version
- Add changelog

Prepare 1.21.0 release

---

pkg/api/mock.go
pkg/api/mock/client.go
pkg/api/mock/client_test.go

Adds a new mock client to match a set of responses per endpoint. The match is done using a regex.
https://elasticco.atlassian.net/browse/CP-7863
In PR https://github.com/elastic/cloud-cli/pull/1525, I added some unit tests that are currently failing because they're using the default Round Tripper client. This client provides the responses in the order they're defined. However, in those tests we're not sure in which order the requests are executed, because they're performed by different go routines running concurrently. This new client allows to provide a set of responses per endpoint, by specifying an endpoint regex as the key to a map and a set of responses as the value.

Add new mock client to match responses by endpoint

---

.changelog/1.22.0/485.yml
Makefile
NOTICE
notes/v1.22.0.md

Update version in Makefile and add changelog entry for 1.22.0.
The changes to `NOTICE` were generated automatically by `make format changelog`.

Updates for release 1.22.0

---

.changelog/1.24.0/495.yml
pkg/api/deploymentapi/search.go
pkg/api/deploymentapi/search_test.go

This parameter will change the response to only include the passed in fields.
This is very useful as by default the response contains all deployment-related fields leading to quite large responses. If one only needs a few fields like the id, the `minimal_metadata` field can greatly reduce the response size.

Deployments search: Add support for `minimal_metadata` parameter.

---

pkg/api/client_runtime.go
pkg/api/client_runtime_test.go
pkg/api/platformapi/info.go
pkg/api/platformapi/info_test.go

* the get-platform operation can be called in a region bound context and also in a region less context.
* the main use case of calling it regionless is to discover regions
The platform capacity team intends to move fully away of the internal-cloud-sdk-go and so far we were blocked by the GetPlatform call not be available in the regionless context. This is used to discover all cloud regions (https://github.com/elastic/internal-cloud-sdk-go/blob/master/pkg/api/platformapi/info.go)  
* extended test coverage
* used in [elastic/jit](https://github.com/elastic/jit) autoscaling

fix(client_runtime): allow get-platform request to have regionless runtime
